import React, { Component } from 'react';
import {
	Text,
	View,
	StyleSheet,
	Image,
	TextInput,
	TouchableNativeFeedback,
	ScrollView,
	Alert,
	Dimensions,
	NativeModules
} from 'react-native';
import { bindMethods } from '../../utils';
import st from '../../assets/style';
import FontAwesomeIcon from 'react-native-vector-icons/FontAwesome';
import TabIcons from '../../components/TabIcons'
import BuyerProfileHeader from '../../components/BuyerProfileHeader';
import { createIconSet } from 'react-native-vector-icons';


export default class DashboardBuyer extends Component {

	constructor(prop) {
		super(prop);
		bindMethods(this);

		this.iconsMap = {
			news	 	:59652,
			coupons 	:59653,
			stores	 	:59677,
		};

    	this.Icon = createIconSet(this.iconsMap, 'icomoon2' );


		// console.log(this.props.localNotification);

		// PushNotification().localNotification({
		//     // id: '0', // (optional) Valid unique 32 bit integer specified as string. default: Autogenerated Unique ID
		//     // ticker: "My Notification Ticker", // (optional)
		//     autoCancel: true, // (optional) default: true
		//     largeIcon: "ic_launcher", // (optional) default: "ic_launcher"
		//     // smallIcon: "ic_notification", // (optional) default: "ic_notification" with fallback for "ic_launcher"
		//     bigText: "My big text that will be shown when notification is expanded", // (optional) default: "message" prop
		//     // subText: "This is a subText", // (optional) default: none
		//     // color: "red", // (optional) default: system default
		//     vibrate: true, // (optional) default: true
		//     vibration: 300, // vibration length in milliseconds, ignored if vibrate=false, default: 1000
		//     tag: 'checkout', // (optional) add tag to message
		//     group: "group", // (optional) add group to message
		//     ongoing: false, // (optional) set whether this is an "ongoing" notification

		//     title: "My Notification Title", // (optional, for iOS this is only used in apple watch, the title will be the app name on other iOS devices)
		//     message: "My Notification Message", // (required)
		//     soundName: 'default', // (optional) Sound to play when the notification is shown. Value of 'default' plays the default sound. It can be set to a custom sound such as 'android.resource://com.xyz/raw/my_sound'. It will look for the 'my_sound' audio file in 'res/raw' directory and play it. default: 'default' (default sound is played)
		// })


		/*console.log(PushNotification);

			
		PushNotification.localNotification({
		    // id: '0', // (optional) Valid unique 32 bit integer specified as string. default: Autogenerated Unique ID
		    // ticker: "My Notification Ticker", // (optional)
		    autoCancel: false, // (optional) default: true
		    largeIcon: "ic_launcher", // (optional) default: "ic_launcher"
		    // smallIcon: "ic_notification", // (optional) default: "ic_notification" with fallback for "ic_launcher"
		    bigText: "My big text that will be shown when notification is expanded", // (optional) default: "message" prop
		    // subText: "This is a subText", // (optional) default: none
		    // color: "red", // (optional) default: system default
		    vibrate: true, // (optional) default: true
		    vibration: 300, // vibration length in milliseconds, ignored if vibrate=false, default: 1000
		    tag: 'checkout', // (optional) add tag to message
		    group: "group", // (optional) add group to message
		    ongoing: false, // (optional) set whether this is an "ongoing" notification

		    title: "My Notification Title", // (optional, for iOS this is only used in apple watch, the title will be the app name on other iOS devices)
		    message: "My Notification Message", // (required)
		    soundName: 'default', // (optional) Sound to play when the notification is shown. Value of 'default' plays the default sound. It can be set to a custom sound such as 'android.resource://com.xyz/raw/my_sound'. It will look for the 'my_sound' audio file in 'res/raw' directory and play it. default: 'default' (default sound is played)
		});
		*/
	}

	render() {

		let { Icon } = this;
		const fbData = this.props.manager.getDataFB();



		return (
			<View style={dashSellerStyle.container} >
				<ScrollView>

				
					{/*<View style={dashSellerStyle.topbar}>
						<TouchableNativeFeedback onPress={ () => { this.props.navigator.toBack() } } >
							<View style={dashSellerStyle.buttBack} >
							<FontAwesomeIcon
								name="angle-left"
								style={ { textAlign: 'center', fontSize: 20 } } />
							</View>
						</TouchableNativeFeedback>

						<View style={ dashSellerStyle.title } >
							<Text style={ dashSellerStyle.topbarText } >HOME</Text>
						</View>

						<TouchableNativeFeedback onPress={ () => { Alert.alert('opening basket handler') } } >
							<View style={dashSellerStyle.buttBack} >
								<FontAwesomeIcon
									name="shopping-basket"
									style={ { textAlign: 'center', fontSize: 20 } } />
								
							</View>
						</TouchableNativeFeedback>

					</View> */}


					{/*<View style={ dashSellerStyle.shopTitleView } >
						<View style={dashSellerStyle.shopTitleProfileBlock}>

						    <View style={dashSellerStyle.shopperImgProfile}>
						    	<Image source={{uri: `http://graph.facebook.com/298288423897442/picture?type=large` }} style={st.shopProfileImg}/>
						    	<Text style={ dashSellerStyle.shopperName } >FirstName LastName</Text>
						    </View>

						    <View style={dashSellerStyle.shopperPropsProfile} >
							    <View style={dashSellerStyle.alignCenter} >
							    	<Text style={dashSellerStyle.textPropValue } >106</Text>
							    </View>
							    
						    	<Text style={dashSellerStyle.textPropDesc} >Items Bought</Text>
						    </View>

						    <View style={dashSellerStyle.shopperPropsProfile} >
							    <View style={dashSellerStyle.alignCenter} >
							    	<Text style={dashSellerStyle.textPropValue } >47</Text>
							    </View>
							    
							    <Text style={dashSellerStyle.textPropDesc} >Items Bought</Text>
						    </View>

					        <View style={dashSellerStyle.shopperPropsProfile} >
							    <View style={dashSellerStyle.alignCenter} >
					    	    	<Text style={dashSellerStyle.textPropValue } >23</Text>
							    </View>
					    	    
					    	    <Text style={dashSellerStyle.textPropDesc} >Items Bought</Text>
					        </View>


					  	</View>
				  	</View>*/}

				  	<BuyerProfileHeader pictureSource={ { uri: fbData.profileImgUri } } />

					{/*<View style={ dashSellerStyle.shopTitleView } >
						<View style={dashSellerStyle.shopTitleProfileBlock}>

						    <View style={dashSellerStyle.shopperImgProfile}>
						    	<Image source={{uri: `http://graph.facebook.com/298288423897442/picture?type=large` }} style={st.shopProfileImg}/>
						    	<Text style={ dashSellerStyle.shopperName } >FirstName LastName</Text>
						    </View>

						    <View style={dashSellerStyle.shopperPropsProfile} >
							    <View style={dashSellerStyle.alignCenter} >
							    	<Text style={dashSellerStyle.textPropValue } >106</Text>
							    </View>
							    
						    	<Text style={dashSellerStyle.textPropDesc} >Items Bought</Text>
						    </View>

						    <View style={dashSellerStyle.shopperPropsProfile} >
							    <View style={dashSellerStyle.alignCenter} >
							    	<Text style={dashSellerStyle.textPropValue } >47</Text>
							    </View>
							    
							    <Text style={dashSellerStyle.textPropDesc} >Items Bought</Text>
						    </View>

					        <View style={dashSellerStyle.shopperPropsProfile} >
							    <View style={dashSellerStyle.alignCenter} >
					    	    	<Text style={dashSellerStyle.textPropValue } >23</Text>
							    </View>
					    	    
					    	    <Text style={dashSellerStyle.textPropDesc} >Items Bought</Text>
					        </View>


					  	</View>
				  	</View>*/}

					<TabIcons >
						<View style={dashSellerStyle.tabContent} icon={ <Icon 
								name="news" 
								style={ { textAlign: 'center', fontSize: 23, padding: 5, flex: 1 } }/> } 

							iconActive={ <Icon 
								name="news" 
								style={ { textAlign: 'center', fontSize: 23, padding: 5, color: 'purple', flex: 1 } } /> } >

							<View style={dashSellerStyle.contentRow} >
								
								<View>
									<Text style={dashSellerStyle.blockName}>DEAL OF THE DAY</Text>
								</View>

								<View style={dashSellerStyle.dealDay} >
								   	<Image source={{uri: `http://pipsum.com/435x310.jpg` }} style={dashSellerStyle.dealDayImg}/>

								   	<View style={dashSellerStyle.dealDayContent} >
								   		<Text style={ { color: 'white', fontSize: 18 } } >AN ICON REMASTERED</Text>
								   		<Text style={ { color: 'white',  fontSize: 12 } } >THE BEATS BY DR DRE STUDIO 2 OVER-EAR HEADPHONES</Text>

										<TouchableNativeFeedback onPress={ () => { Alert.alert('buy now') } }>

									   		<View style={ dashSellerStyle.dealDayButtonRow } >
										   		<View style={ dashSellerStyle.dealDayButton } >
										   			<Text style={ { color: 'white', fontSize: 10 } } >BUY NOW 20% OFF</Text>
										   		</View>
									   		</View>
										
										</TouchableNativeFeedback>

								   	</View>
								</View>

							</View>


							<View style={dashSellerStyle.contentRow}>
								
								<View>
									<Text style={dashSellerStyle.blockName}>BEST SELLERS</Text>
								</View>

								<View style={dashSellerStyle.productList}>

									<ScrollView horizontal={true}>

										
										<View style={dashSellerStyle.productItem} >
										   		<Image source={{uri: `http://pipsum.com/435x311.jpg` }} style={dashSellerStyle.productImg}/>
											<View style={dashSellerStyle.productDesc} >
												<View>
													<Text style= { dashSellerStyle.productName } >Backpack Black</Text>
												</View>
												<Text style= { dashSellerStyle.productPrice } >$299.00</Text>
											</View>
										</View>

										<View style={dashSellerStyle.productItem} >
										   		<Image source={{uri: `http://pipsum.com/435x312.jpg` }} style={dashSellerStyle.productImg}/>
											<View style={dashSellerStyle.productDesc} >
												<View>
													<Text style= { dashSellerStyle.productName } >Backpack Black</Text>
												</View>
												<Text style= { dashSellerStyle.productPrice } >$199.00</Text>
											</View>
										</View>

										<View style={dashSellerStyle.productItem} >
										   		<Image source={{uri: `http://pipsum.com/435x313.jpg` }} style={dashSellerStyle.productImg}/>
											<View style={dashSellerStyle.productDesc} >
												<View>
													<Text style= { dashSellerStyle.productName } >Backpack Black</Text>
												</View>
												<Text style= { dashSellerStyle.productPrice } >$399.00</Text>
											</View>
										</View>

										<View style={dashSellerStyle.productItem} >
										   		<Image source={{uri: `http://pipsum.com/435x314.jpg` }} style={dashSellerStyle.productImg}/>
											<View style={dashSellerStyle.productDesc} >
												<View>
													<Text style= { dashSellerStyle.productName } >Backpack Black</Text>
												</View>
												<Text style= { dashSellerStyle.productPrice } >$299.00</Text>
											</View>
										</View>

										<View style={dashSellerStyle.productItem} >
										   		<Image source={{uri: `http://pipsum.com/435x315.jpg` }} style={dashSellerStyle.productImg}/>
											<View style={dashSellerStyle.productDesc} >
												<View>
													<Text style= { dashSellerStyle.productName } >Backpack Black</Text>
												</View>
												<Text style= { dashSellerStyle.productPrice } >$299.00</Text>
											</View>
										</View>

									
									</ScrollView>

								</View>
							</View>

							<View style={dashSellerStyle.contentRow}>
								<View>
									<Text style={dashSellerStyle.blockName}>FEATURED STORE</Text>
								</View>

								<View style={dashSellerStyle.featuredRow} >
									<View style={dashSellerStyle.featuredBlock}>
										<Text style={dashSellerStyle.featuredDesc}>
											Your Style Guide to Winter Clothes Shopping with the founder of @mm_ShopBop
										</Text>
									</View>
				
									<View style={dashSellerStyle.featuredImgBlock}>
										<Image source={{uri: `http://pipsum.com/435x316.jpg` }} style={dashSellerStyle.featuredImg}/>
									</View>

								</View>
							</View>


							<View style={dashSellerStyle.contentRow}>
								<View>
									<Text style={dashSellerStyle.blockName}>WE THOUGHT YOU MIGHT LIKE</Text>
								</View>

								<View style={dashSellerStyle.likeProductList } >

									<View style={dashSellerStyle.likeProductItem}>
										<Image source={{uri: `http://pipsum.com/435x317.jpg?2` }} style={dashSellerStyle.likeProductImg}/>
										<View style={dashSellerStyle.likeProductDescBlock}>
											<Text style={dashSellerStyle.likeProdName}>Boost Band Black Portable Charger Wristband Phone...</Text>

											<View  style={dashSellerStyle.likeProdPriceRow} >
												<View style={dashSellerStyle.likeProdDollIconView} >
													<Text style={dashSellerStyle.likeProdDollarIcon}>$</Text>
												</View>
					
												<Text>29.99</Text>
											</View>
										</View>
									</View>

									<View style={dashSellerStyle.likeProductItem}>
										<Image source={{uri: `http://pipsum.com/435x317.jpg?1` }} style={dashSellerStyle.likeProductImg}/>
										<View style={dashSellerStyle.likeProductDescBlock}>
											<Text style={dashSellerStyle.likeProdName}>Stella 7-speed Internally-geared Luxury Step-through Bicycle...</Text>

											<View  style={dashSellerStyle.likeProdPriceRow} >
												<View style={dashSellerStyle.likeProdDollIconView} >
													<Text style={dashSellerStyle.likeProdDollarIcon}>$</Text>
												</View>
									
												<Text>1,049.00</Text>
											</View>
										</View>
									</View>

									<View style={dashSellerStyle.likeProductItem}>
										<Image source={{uri: `http://pipsum.com/435x319.jpg` }} style={dashSellerStyle.likeProductImg}/>
										<View style={dashSellerStyle.likeProductDescBlock}>
											<Text style={dashSellerStyle.likeProdName}>Nomader BPA Free Collapsible Sports Water Bottle - Foldable...</Text>

											<View  style={dashSellerStyle.likeProdPriceRow} >
												<View style={dashSellerStyle.likeProdDollIconView} >
													<Text style={dashSellerStyle.likeProdDollarIcon}>$</Text>
												</View>
									
												<Text>16.95</Text>
											</View>
										</View>
									</View>

								</View>

							</View>

						</View>

						<View style={dashSellerStyle.tabContent} icon={ <Icon 
								name="coupons" 
								style={ { textAlign: 'center', fontSize: 23, padding: 5, flex: 1 } }/> } 

							iconActive={ <Icon 
								name="coupons" 
								style={ { textAlign: 'center', fontSize: 23, padding: 5, color: 'purple', flex: 1 } }  /> } > 
							<Text>tab 2 </Text>
						</View>

						<View style={dashSellerStyle.tabContent} icon={ <Icon 
								name="stores" 
								style={ { textAlign: 'center', fontSize: 23, padding: 5, flex: 1 } }/> } 

							iconActive={ <Icon 
								name="stores" 
								style={ { textAlign: 'center', fontSize: 23, padding: 5, color: 'purple', flex: 1 } } /> } >

							<Text>tab 3</Text>
						</View>

					</TabIcons>

					
				</ScrollView>
			</View>
		)
	}
}

const dashSellerStyle = StyleSheet.create({
	topbarText: {
		textAlign: 'center',
		fontWeight: '100',
		fontSize: 24,
		color: 'purple',
	},
	buttBack: {
		justifyContent: 'center',
		flex: 1,
	},
	title: {
		justifyContent: 'center',
		flex: 3,
	},
	shopTitleProfileBlock: {
		flexDirection: 'row',
		flex: 1,
		zIndex: 20,
		marginTop: 10,
		marginBottom: 10,
	},
	tabList: {
		borderBottomWidth: 0.5,
		borderTopWidth: 0.5,
		borderColor: '#aaa',
		flexDirection: 'row',
	},
	tabItem: {
		flex: 2,
	},
	tabItemCenter: {
		flex: 3,
	},

	likeProdDollIconView: {
		position: 'absolute',
		top: -2,
		left: 0,
	},
	topbar: {
		flexDirection: 'row',
		height: 50,
		borderBottomWidth: 1,
		justifyContent: 'center',
	},
	likeProdPriceRow: {
		paddingLeft: 7,
	},
	likeProdDollarIcon: {
		fontSize: 11,
	},
	likeProdName: {
		fontWeight: '500',
		color: 'black',
		fontSize: 16,
	},
	likeProductDescBlock: {
		flex: 1,
		paddingLeft: 10,
	},
	likeProductImg: {
		height: 80,
		width: 80,
		resizeMode: 'cover',
	},
	likeProductList: {
		paddingHorizontal: 8,
		borderWidth: 0.5,
		borderColor: '#aaa',
	},
	likeProductItem: {
		paddingTop: 8,
		flex: 1,
		flexDirection: 'row',
	},
	featuredBlock: {
		flex: 1,
		height: 180,
		borderWidth: 0.5,
		borderColor: '#aaa',
		alignItems: 'center',
		justifyContent: 'center',
	},
	featuredImgBlock: {
		height: 180,
		width: 180,
		borderWidth: 0.5,
		borderColor: '#aaa',
		alignItems: 'center',
		justifyContent: 'center',
	},
	featuredImg: {
		height: 180,
		width: 180,
		resizeMode: 'cover',
	},
	featuredDesc: {
		textAlign: 'center',
		padding: 13,
		fontSize: 19,
		fontStyle: 'italic',

	},
	featuredRow: {
		flexDirection: 'row',
	},
	productPrice: {
		paddingTop: 5,
		color: '#783ab1',
		textAlign:'center',
		fontWeight: 'bold',
	},
	productName: {
		color: 'black',
		textAlign:'center',
		fontWeight: 'bold',
	},
	productImg: {
		height: 130,
		width: 130,
    	resizeMode: 'cover',
	},
	productItem: {
		padding: 13,
		borderWidth: 0.5,
		borderColor: '#aaa',
	},
	productDesc: {
		paddingTop: 5,
		alignItems: 'center',
	},
	contentRow: {
		marginTop: 10,
	},
	shopTitleView: {
		justifyContent: 'center',
		paddingHorizontal: 10,
	},
	productList: {
		flexDirection: 'row',
	},
	dealDayButtonRow: {
		flexDirection: 'row',
		paddingTop: 10,
	},
	dealDayButton: {
		backgroundColor: 'rgba(255, 255, 255, 0.15)',
		paddingHorizontal: 15,
		paddingVertical: 8,
		borderWidth: 1,
		borderColor: 'white',
	},
	dealDayContent: {
		zIndex: 20,
		flex: 1,
		paddingHorizontal: 8,
		justifyContent: 'center',
		paddingBottom: 30,
	},
	blockName: {
		fontStyle: 'italic',
		paddingLeft: 8,
	},
	dealDay: {
		height: 180,
	},
	shopperName: {
		textAlign: 'center',
		color: 'black',
	},
	dealDayImg: {
		zIndex: 10,
		flex: 1,
    	resizeMode: 'cover',
    	top: 0,
    	left: 0,
    	right: 0,
    	bottom: 0,
    	position: 'absolute',
    },
	container: {
		flex: 1,
		backgroundColor: `white`,
	},
	shopperImgProfile: {
		flex: 3,
		alignItems: 'center',
	},
	shopperPropsProfile: {
		flex: 2,
		alignItems: 'center',
	},
	textPropDesc: {
		textAlign: 'center',
		color: 'black',
	},
	textPropValue: {
		color: 'black',
		fontSize: 20,
	},
	alignCenter: {
		alignItems: 'center',
	}
});
